version: "3.9"

services:
  lab5-postgres:
    image: postgres:16-alpine
    container_name: lab5-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lab5db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      # данные БД, чтобы не терялись между перезапусками
      - pgdata_lab5:/var/lib/postgresql/data
      - ./manual/src/main/resources/scripts/01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql:ro

  manual-app:
    build:
      context: ./manual
      dockerfile: Dockerfile
    container_name: lab6-manual-app
    restart: unless-stopped
    depends_on:
      - lab5-postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: lab5-postgres
      DB_PORT: 5432
      DB_NAME: lab5db
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  pgdata_lab5:
